seed: 42
device: cuda   # cpu | cuda

data:
  fastq_dir: null             # SELEX fastq file (user set)
  seq_acts: null           # sequence activity csv (seq,activity) (user set)


model:
  InstructNA_model_path: null       # Trained InstructNA model CKPT (user set)
output_dir: ./seeds_construct_output/